site_name: BoFire
site_url: https://experimental-design.github.io/bofire
repo_name: experimental-design/bofire
repo_url: https://github.com/experimental-design/bofire

nav:
  - index.md
  - Install: install.md
  - Notebook page: getting_started.ipynb
  - Advanced Domain Configuration: domain.md
  - Examples: examples.md
  - Strategies: strategies.md
  - Data Models vs Functional Components: data_models_functionals.md
  - Surrogate Models: userguide_surrogates.md
  - API Reference:
    - Domain: ref-domain.md
    - Constraints: ref-constraints.md
    - Objectives: ref-objectives.md
    - Features: ref-features.md
    - Utils: ref-utils.md

theme:
  name: material
  features:
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - bofire

plugins:
  - search
  - mkdocs-jupyter
  # https://mkdocstrings.github.io/
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
  # https://github.com/jimporter/mike
  - mike:

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/math/?h=math#mathjax
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
