"""Documentation ratchet for the data models.

BoFire is configured through its data models, which makes them the API surface for
both humans and agents. The prose therefore belongs where `model_json_schema()` can
see it: `Field(description=...)` for every field, and a docstring on every class.

The allowlists below record what predates that convention. They may only shrink --
`test_field_allowlist_has_no_stale_entries` and its class-level counterpart fail once
an allowlisted entry has been documented (or removed) without being deleted here, so
documenting a package and pruning its entries have to happen in the same commit.
"""

import importlib
import pkgutil
from typing import Dict, List, Type

import pytest
from pydantic import BaseModel

import bofire.data_models


# Fields that do not yet carry `Field(description=...)`. Only ever remove entries.
UNDOCUMENTED_FIELDS = {
    "bofire.data_models.acquisition_functions.acquisition_function.qEHVI.alpha",
    "bofire.data_models.acquisition_functions.acquisition_function.qEHVI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qEI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogEHVI.alpha",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogEHVI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogEI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEHVI.alpha",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEHVI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEHVI.prune_baseline",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEI.prune_baseline",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogPF.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qMFHVKG.alpha",
    "bofire.data_models.acquisition_functions.acquisition_function.qMFHVKG.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qMFHVKG.num_fantasies",
    "bofire.data_models.acquisition_functions.acquisition_function.qMFHVKG.num_pareto",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEHVI.alpha",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEHVI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEHVI.prune_baseline",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEI.prune_baseline",
    "bofire.data_models.acquisition_functions.acquisition_function.qNegIntPosVar.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qNegIntPosVar.weights",
    "bofire.data_models.acquisition_functions.acquisition_function.qPI.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qPI.tau",
    "bofire.data_models.acquisition_functions.acquisition_function.qSR.n_mc_samples",
    "bofire.data_models.acquisition_functions.acquisition_function.qUCB.beta",
    "bofire.data_models.acquisition_functions.acquisition_function.qUCB.n_mc_samples",
    "bofire.data_models.dataframes.dataframes.CandidateOutputValue.objective_value",
    "bofire.data_models.dataframes.dataframes.CandidateOutputValue.standard_deviation",
    "bofire.data_models.dataframes.dataframes.DataFrame.rows",
    "bofire.data_models.dataframes.dataframes.ExperimentOutputValue.valid",
    "bofire.data_models.dataframes.dataframes.OutputValue.value",
    "bofire.data_models.dataframes.dataframes.Row.inputs",
    "bofire.data_models.dataframes.dataframes.Row.outputs",
    "bofire.data_models.descriptor_generators.generators.Fingerprints.bond_radius",
    "bofire.data_models.descriptor_generators.generators.Fingerprints.n_bits",
    "bofire.data_models.descriptor_generators.generators.Fragments.fragments",
    "bofire.data_models.descriptor_generators.generators.MordredDescriptors.descriptors",
    "bofire.data_models.descriptor_generators.generators.MordredDescriptors.ignore_3D",
    "bofire.data_models.domain.constraints.Constraints.constraints",
    "bofire.data_models.domain.domain.Domain.constraints",
    "bofire.data_models.domain.domain.Domain.context",
    "bofire.data_models.domain.domain.Domain.inputs",
    "bofire.data_models.domain.domain.Domain.outputs",
    "bofire.data_models.domain.features._BaseFeatures.features",
    "bofire.data_models.encodings.onehot.OneHotEncoding.drop_first",
    "bofire.data_models.features._descriptor_spec.DescriptorSpec.columns",
    "bofire.data_models.features._descriptor_spec.DescriptorSpec.correlation_cutoff",
    "bofire.data_models.features._descriptor_spec.DescriptorSpec.filter_descriptors",
    "bofire.data_models.features._descriptor_spec.DescriptorSpec.generators",
    "bofire.data_models.features.categorical.CategoricalInput.allowed",
    "bofire.data_models.features.categorical.CategoricalInput.categories",
    "bofire.data_models.features.categorical.CategoricalInput.descriptors",
    "bofire.data_models.features.categorical.CategoricalOutput.categories",
    "bofire.data_models.features.categorical.CategoricalOutput.objective",
    "bofire.data_models.features.continuous.ContinuousInput.allow_zero",
    "bofire.data_models.features.continuous.ContinuousInput.bounds",
    "bofire.data_models.features.continuous.ContinuousInput.local_relative_bounds",
    "bofire.data_models.features.continuous.ContinuousInput.stepsize",
    "bofire.data_models.features.continuous.ContinuousOutput.objective",
    "bofire.data_models.features.continuous.ContinuousOutput.unit",
    "bofire.data_models.features.descriptors.Descriptors.columns",
    "bofire.data_models.features.descriptors.Descriptors.structure",
    "bofire.data_models.features.discrete.DiscreteInput.rtol",
    "bofire.data_models.features.discrete.DiscreteInput.values",
    "bofire.data_models.features.engineered_feature.CloneFeature.features",
    "bofire.data_models.features.engineered_feature.EngineeredFeature.features",
    "bofire.data_models.features.engineered_feature.EngineeredFeature.keep_features",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.append_x",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.append_y",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.interpolation_range",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.n_interpolation_points",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.normalize_x",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.normalize_y",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.prepend_x",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.prepend_y",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.x_keys",
    "bofire.data_models.features.engineered_feature.InterpolateFeature.y_keys",
    "bofire.data_models.features.engineered_feature.ProductFeature.features",
    "bofire.data_models.features.engineered_feature.WeightedSumFeature.normalize",
    "bofire.data_models.features.feature.Feature.context",
    "bofire.data_models.features.feature.Feature.key",
    "bofire.data_models.features.numerical.NumericalInput.descriptors",
    "bofire.data_models.features.numerical.NumericalInput.unit",
    "bofire.data_models.features.task.CategoricalTaskInput.descriptors",
    "bofire.data_models.features.task.CategoricalTaskInput.fidelities",
    "bofire.data_models.features.task.ContinuousTaskInput.descriptors",
    "bofire.data_models.kernels.aggregation.AdditiveKernel.kernels",
    "bofire.data_models.kernels.aggregation.MultiplicativeKernel.kernels",
    "bofire.data_models.kernels.aggregation.PolynomialFeatureInteractionKernel.include_self_interactions",
    "bofire.data_models.kernels.aggregation.PolynomialFeatureInteractionKernel.kernels",
    "bofire.data_models.kernels.aggregation.PolynomialFeatureInteractionKernel.max_degree",
    "bofire.data_models.kernels.aggregation.PolynomialFeatureInteractionKernel.outputscale_prior",
    "bofire.data_models.kernels.aggregation.ScaleKernel.base_kernel",
    "bofire.data_models.kernels.aggregation.ScaleKernel.outputscale_constraint",
    "bofire.data_models.kernels.aggregation.ScaleKernel.outputscale_prior",
    "bofire.data_models.kernels.categorical.HammingDistanceKernel.ard",
    "bofire.data_models.kernels.categorical.HammingDistanceKernel.lengthscale_constraint",
    "bofire.data_models.kernels.categorical.HammingDistanceKernel.lengthscale_prior",
    "bofire.data_models.kernels.categorical.IndexKernel.num_categories",
    "bofire.data_models.kernels.categorical.IndexKernel.prior",
    "bofire.data_models.kernels.categorical.IndexKernel.rank",
    "bofire.data_models.kernels.categorical.IndexKernel.var_constraint",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.diag_prior",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.normalize_covar_matrix",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.num_categories",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.prior",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.rank",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.target_task_index",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.task_prior",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.unit_scale_for_target",
    "bofire.data_models.kernels.categorical.PositiveIndexKernel.var_constraint",
    "bofire.data_models.kernels.conditional.ConditionalEmbeddingKernel.base_kernel",
    "bofire.data_models.kernels.conditional.ConditionalEmbeddingKernel.conditions",
    "bofire.data_models.kernels.conditional.WedgeKernel.angle_prior",
    "bofire.data_models.kernels.conditional.WedgeKernel.ard",
    "bofire.data_models.kernels.conditional.WedgeKernel.lengthscale_constraint",
    "bofire.data_models.kernels.conditional.WedgeKernel.lengthscale_prior",
    "bofire.data_models.kernels.conditional.WedgeKernel.radius_prior",
    "bofire.data_models.kernels.continuous.InfiniteWidthBNNKernel.depth",
    "bofire.data_models.kernels.continuous.InfiniteWidthBNNKernel.features",
    "bofire.data_models.kernels.continuous.LinearKernel.variance_prior",
    "bofire.data_models.kernels.continuous.MaternKernel.ard",
    "bofire.data_models.kernels.continuous.MaternKernel.lengthscale_constraint",
    "bofire.data_models.kernels.continuous.MaternKernel.lengthscale_prior",
    "bofire.data_models.kernels.continuous.MaternKernel.nu",
    "bofire.data_models.kernels.continuous.PolynomialKernel.offset_prior",
    "bofire.data_models.kernels.continuous.PolynomialKernel.power",
    "bofire.data_models.kernels.continuous.RBFKernel.ard",
    "bofire.data_models.kernels.continuous.RBFKernel.lengthscale_constraint",
    "bofire.data_models.kernels.continuous.RBFKernel.lengthscale_prior",
    "bofire.data_models.kernels.continuous.SphericalLinearKernel.ard",
    "bofire.data_models.kernels.continuous.SphericalLinearKernel.bounds",
    "bofire.data_models.kernels.continuous.SphericalLinearKernel.lengthscale_constraint",
    "bofire.data_models.kernels.continuous.SphericalLinearKernel.lengthscale_prior",
    "bofire.data_models.kernels.fidelity.DownsamplingKernel.offset_constraint",
    "bofire.data_models.kernels.fidelity.DownsamplingKernel.offset_prior",
    "bofire.data_models.kernels.fidelity.DownsamplingKernel.power_constraint",
    "bofire.data_models.kernels.fidelity.DownsamplingKernel.power_prior",
    "bofire.data_models.kernels.kernel.FeatureSpecificKernel.features",
    "bofire.data_models.kernels.molecular.TanimotoKernel.ard",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.append_x",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.append_y",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.idx_x",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.idx_y",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.lengthscale_constraint",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.lengthscale_prior",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.normalize_x",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.normalize_y",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.order",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.prepend_x",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.prepend_y",
    "bofire.data_models.kernels.shape.ExactWassersteinKernel.squared",
    "bofire.data_models.kernels.shape.WassersteinKernel.lengthscale_constraint",
    "bofire.data_models.kernels.shape.WassersteinKernel.lengthscale_prior",
    "bofire.data_models.kernels.shape.WassersteinKernel.squared",
    "bofire.data_models.llm.provider.AnthropicFoundryLLMProvider.api_key_env_var",
    "bofire.data_models.llm.provider.AnthropicFoundryLLMProvider.model",
    "bofire.data_models.llm.provider.AnthropicFoundryLLMProvider.resource_env_var",
    "bofire.data_models.llm.provider.AnthropicLLMProvider.api_key_env_var",
    "bofire.data_models.llm.provider.AnthropicLLMProvider.model",
    "bofire.data_models.llm.provider.LLMProvider.api_key_env_var",
    "bofire.data_models.llm.provider.LLMProvider.model",
    "bofire.data_models.llm.provider.OpenAICompatibleLLMProvider.api_key_env_var",
    "bofire.data_models.llm.provider.OpenAICompatibleLLMProvider.base_url",
    "bofire.data_models.llm.provider.OpenAICompatibleLLMProvider.model",
    "bofire.data_models.llm.provider.OpenAILLMProvider.api_key_env_var",
    "bofire.data_models.llm.provider.OpenAILLMProvider.model",
    "bofire.data_models.strategies.convergence_criteria.hypervolume_improvement.HypervolumeImprovementCriterion.min_improvement",
    "bofire.data_models.strategies.convergence_criteria.hypervolume_improvement.HypervolumeImprovementCriterion.n_lookback",
    "bofire.data_models.strategies.convergence_criteria.objective_improvement.ObjectiveImprovementCriterion.min_improvement",
    "bofire.data_models.strategies.convergence_criteria.objective_improvement.ObjectiveImprovementCriterion.n_lookback",
    "bofire.data_models.strategies.convergence_criteria.proposal_deviation.ProposalDeviationCriterion.n_consecutive",
    "bofire.data_models.strategies.convergence_criteria.proposal_deviation.ProposalDeviationCriterion.threshold",
    "bofire.data_models.strategies.doe.DoEOptimalityCriterion.formula",
    "bofire.data_models.strategies.doe.DoEStrategy.criterion",
    "bofire.data_models.strategies.doe.DoEStrategy.ipopt_options",
    "bofire.data_models.strategies.doe.DoEStrategy.return_fixed_candidates",
    "bofire.data_models.strategies.doe.DoEStrategy.sampling",
    "bofire.data_models.strategies.doe.DoEStrategy.scip_params",
    "bofire.data_models.strategies.doe.DoEStrategy.use_cyipopt",
    "bofire.data_models.strategies.doe.DoEStrategy.use_hessian",
    "bofire.data_models.strategies.doe.DoEStrategy.verbose",
    "bofire.data_models.strategies.doe.IOptimalityCriterion.ipopt_options",
    "bofire.data_models.strategies.doe.IOptimalityCriterion.n_space_filling_points",
    "bofire.data_models.strategies.doe.OptimalityCriterion.delta",
    "bofire.data_models.strategies.doe.OptimalityCriterion.transform_range",
    "bofire.data_models.strategies.doe.SpaceFillingCriterion.sampling_fraction",
    "bofire.data_models.strategies.fractional_factorial.FractionalFactorialStrategy.block_feature_key",
    "bofire.data_models.strategies.llm.LLMStrategy.llm",
    "bofire.data_models.strategies.llm.LLMStrategy.model_settings",
    "bofire.data_models.strategies.llm.LLMStrategy.n_recent_experiments",
    "bofire.data_models.strategies.llm.LLMStrategy.n_top_experiments",
    "bofire.data_models.strategies.llm.LLMStrategy.output_retries",
    "bofire.data_models.strategies.llm.LLMStrategy.system_prompt",
    "bofire.data_models.strategies.predictives.acqf_optimization.AcquisitionOptimizer.prefer_exhaustive_search_for_purely_categorical_domains",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.batch_limit",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.local_search_config",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.maxiter",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.n_raw_samples",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.n_restarts",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer.sequential",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.cvtol",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.ftol",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.n_max_evals",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.n_max_gen",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.population_size",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.verbose",
    "bofire.data_models.strategies.predictives.acqf_optimization.GeneticAlgorithmOptimizer.xtol",
    "bofire.data_models.strategies.predictives.acqf_optimization.LSRBO.gamma",
    "bofire.data_models.strategies.predictives.active_learning.ActiveLearningStrategy.acquisition_function",
    "bofire.data_models.strategies.predictives.botorch.BotorchStrategy.acquisition_optimizer",
    "bofire.data_models.strategies.predictives.botorch.BotorchStrategy.folds",
    "bofire.data_models.strategies.predictives.botorch.BotorchStrategy.frequency_hyperopt",
    "bofire.data_models.strategies.predictives.botorch.BotorchStrategy.surrogate_specs",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.acq_sense",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.beta",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.bound_coeff",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.cat_metric",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.dist_metric",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.dist_trafo",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.kappa_fantasy",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.max_depth",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.min_data_in_leaf",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.min_data_per_group",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.num_boost_round",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.solver_name",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.solver_params",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.solver_verbose",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy.verbose",
    "bofire.data_models.strategies.predictives.mobo.AbsoluteMovingReferenceValue.offset",
    "bofire.data_models.strategies.predictives.mobo.AbsoluteMovingReferenceValue.orient_at_best",
    "bofire.data_models.strategies.predictives.mobo.ExplicitReferencePoint.values",
    "bofire.data_models.strategies.predictives.mobo.FixedReferenceValue.value",
    "bofire.data_models.strategies.predictives.mobo.MoboStrategy.acquisition_function",
    "bofire.data_models.strategies.predictives.mobo.MoboStrategy.ref_point",
    "bofire.data_models.strategies.predictives.mobo.RelativeMovingReferenceValue.orient_at_best",
    "bofire.data_models.strategies.predictives.mobo.RelativeMovingReferenceValue.scaling",
    "bofire.data_models.strategies.predictives.mobo.RelativeToMaxMovingReferenceValue.orient_at_best",
    "bofire.data_models.strategies.predictives.mobo.RelativeToMaxMovingReferenceValue.scaling",
    "bofire.data_models.strategies.predictives.multi_fidelity.MultiFidelityVarianceBasedStrategy.fidelity_thresholds",
    "bofire.data_models.strategies.predictives.multi_fidelity_knowledge_gradient.MultiFidelityHVKGStrategy.acquisition_function",
    "bofire.data_models.strategies.predictives.multi_fidelity_knowledge_gradient.MultiFidelityHVKGStrategy.fidelity_cost_model_spec",
    "bofire.data_models.strategies.predictives.predictive.PredictiveStrategy.convergence_criterion",
    "bofire.data_models.strategies.predictives.qparego.QparegoStrategy.acquisition_function",
    "bofire.data_models.strategies.predictives.sobo.AdditiveSoboStrategy.use_output_constraints",
    "bofire.data_models.strategies.predictives.sobo.CustomSoboStrategy.dump",
    "bofire.data_models.strategies.predictives.sobo.CustomSoboStrategy.use_output_constraints",
    "bofire.data_models.strategies.predictives.sobo.MultiplicativeAdditiveSoboStrategy.additive_features",
    "bofire.data_models.strategies.predictives.sobo.MultiplicativeAdditiveSoboStrategy.use_output_constraints",
    "bofire.data_models.strategies.predictives.sobo.SoboBaseStrategy.acquisition_function",
    "bofire.data_models.strategies.random.RandomStrategy.fallback_sampling_method",
    "bofire.data_models.strategies.random.RandomStrategy.max_combinations",
    "bofire.data_models.strategies.random.RandomStrategy.max_iters",
    "bofire.data_models.strategies.random.RandomStrategy.n_burnin",
    "bofire.data_models.strategies.random.RandomStrategy.n_thinning",
    "bofire.data_models.strategies.random.RandomStrategy.nchoosek_max_iters",
    "bofire.data_models.strategies.random.RandomStrategy.num_base_samples",
    "bofire.data_models.strategies.random.RandomStrategy.sampler_kwargs",
    "bofire.data_models.strategies.shortest_path.ShortestPathStrategy.atol",
    "bofire.data_models.strategies.shortest_path.ShortestPathStrategy.end",
    "bofire.data_models.strategies.shortest_path.ShortestPathStrategy.start",
    "bofire.data_models.strategies.stepwise.conditions.CombiCondition.conditions",
    "bofire.data_models.strategies.stepwise.conditions.CombiCondition.n_required_conditions",
    "bofire.data_models.strategies.stepwise.conditions.FeasibleExperimentCondition.n_required_feasible_experiments",
    "bofire.data_models.strategies.stepwise.conditions.FeasibleExperimentCondition.threshold",
    "bofire.data_models.strategies.stepwise.conditions.NumberOfExperimentsCondition.n_experiments",
    "bofire.data_models.strategies.stepwise.stepwise.Step.condition",
    "bofire.data_models.strategies.stepwise.stepwise.Step.strategy_data",
    "bofire.data_models.strategies.stepwise.stepwise.Step.transform",
    "bofire.data_models.strategies.stepwise.stepwise.StepwiseStrategy.steps",
    "bofire.data_models.strategies.strategy.Strategy.domain",
    "bofire.data_models.strategies.strategy.Strategy.seed",
    "bofire.data_models.surrogates.bnn.SingleTaskIBNNSurrogate.hyperconfig",
    "bofire.data_models.surrogates.bnn.SingleTaskIBNNSurrogate.kernel",
    "bofire.data_models.surrogates.botorch.BotorchSurrogate.categorical_encodings",
    "bofire.data_models.surrogates.botorch.BotorchSurrogate.engineered_features",
    "bofire.data_models.surrogates.botorch_surrogates.BotorchSurrogates.surrogates",
    "bofire.data_models.surrogates.deterministic.CategoricalDeterministicSurrogate.mapping",
    "bofire.data_models.surrogates.deterministic.LinearDeterministicSurrogate.coefficients",
    "bofire.data_models.surrogates.deterministic.LinearDeterministicSurrogate.intercept",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate.features_to_warp",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate.model_type",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate.num_samples",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate.thinning",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate.warmup_steps",
    "bofire.data_models.surrogates.linear.LinearSurrogate.kernel",
    "bofire.data_models.surrogates.linear.LinearSurrogate.noise_constraint",
    "bofire.data_models.surrogates.linear.LinearSurrogate.noise_prior",
    "bofire.data_models.surrogates.map_saas.AdditiveMapSaasSingleTaskGPSurrogate.n_taus",
    "bofire.data_models.surrogates.map_saas.EnsembleMapSaasSingleTaskGPSurrogate.n_taus",
    "bofire.data_models.surrogates.map_saas.EnsembleMapSaasSingleTaskGPSurrogate.output_scaler",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPHyperconfig.hyperstrategy",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPHyperconfig.inputs",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPHyperconfig.target_metric",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate.categorical_kernel",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate.continuous_kernel",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate.hyperconfig",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate.noise_constraint",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate.noise_prior",
    "bofire.data_models.surrogates.mlp.ClassificationMLPEnsemble.final_activation",
    "bofire.data_models.surrogates.mlp.ClassificationMLPEnsemble.output_scaler",
    "bofire.data_models.surrogates.mlp.ClassificationMLPEnsemble.scaler",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.activation",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.batch_size",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.dropout",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.hidden_layer_sizes",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.lr",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.n_epochs",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.n_estimators",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.shuffle",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.subsample_fraction",
    "bofire.data_models.surrogates.mlp.MLPEnsemble.weight_decay",
    "bofire.data_models.surrogates.mlp.RegressionMLPEnsemble.final_activation",
    "bofire.data_models.surrogates.mlp.RegressionMLPEnsemble.output_scaler",
    "bofire.data_models.surrogates.mlp.RegressionMLPEnsemble.scaler",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPHyperconfig.hyperstrategy",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPHyperconfig.inputs",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPHyperconfig.target_metric",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate.hyperconfig",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate.kernel",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate.noise_constraint",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate.noise_prior",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate.task_prior",
    "bofire.data_models.surrogates.pairwise_gp.PairwiseGPSurrogate.kernel",
    "bofire.data_models.surrogates.pairwise_gp.PairwiseGPSurrogate.likelihood",
    "bofire.data_models.surrogates.pairwise_gp.PairwiseGPSurrogate.scaler",
    "bofire.data_models.surrogates.polynomial.PolynomialSurrogate.kernel",
    "bofire.data_models.surrogates.polynomial.PolynomialSurrogate.noise_constraint",
    "bofire.data_models.surrogates.polynomial.PolynomialSurrogate.noise_prior",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.bootstrap",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.ccp_alpha",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.criterion",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.max_depth",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.max_features",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.max_leaf_nodes",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.max_samples",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.min_impurity_decrease",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.min_samples_leaf",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.min_samples_split",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.min_weight_fraction_leaf",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.n_estimators",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.oob_score",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate.random_state",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.cache_model_trace",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.convex_parametrization",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.hyperconfig",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.kernel",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.noise_constraint",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.noise_prior",
    "bofire.data_models.surrogates.robust_single_task_gp.RobustSingleTaskGPSurrogate.prior_mean_of_support",
    "bofire.data_models.surrogates.scaler.Scaler.features",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig.hyperstrategy",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig.inputs",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig.lengthscale_constraint",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig.outputscale_constraint",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig.target_metric",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPSurrogate.hyperconfig",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPSurrogate.kernel",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPSurrogate.noise_constraint",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPSurrogate.noise_prior",
    "bofire.data_models.surrogates.surrogate.Surrogate.dump",
    "bofire.data_models.surrogates.surrogate.Surrogate.inputs",
    "bofire.data_models.surrogates.surrogate.Surrogate.outputs",
    "bofire.data_models.surrogates.tanimoto_gp.TanimotoGPSurrogate.kernel",
    "bofire.data_models.surrogates.tanimoto_gp.TanimotoGPSurrogate.noise_constraint",
    "bofire.data_models.surrogates.tanimoto_gp.TanimotoGPSurrogate.noise_prior",
    "bofire.data_models.surrogates.tanimoto_gp.TanimotoGPSurrogate.tanimoto_calculation_mode",
    "bofire.data_models.surrogates.trainable.Hyperconfig.hyperstrategy",
    "bofire.data_models.surrogates.trainable.Hyperconfig.inputs",
    "bofire.data_models.surrogates.trainable.Hyperconfig.n_iterations",
    "bofire.data_models.surrogates.trainable.Hyperconfig.target_metric",
    "bofire.data_models.surrogates.trainable.TrainableSurrogate.hyperconfig",
    "bofire.data_models.surrogates.trainable_botorch.TrainableBotorchSurrogate.output_scaler",
    "bofire.data_models.surrogates.trainable_botorch.TrainableBotorchSurrogate.scaler",
    "bofire.data_models.transforms.drop_data.DropDataTransform.to_be_removed_candidates",
    "bofire.data_models.transforms.drop_data.DropDataTransform.to_be_removed_experiments",
    "bofire.data_models.transforms.manipulate_data.ManipulateDataTransform.candidate_transforms",
    "bofire.data_models.transforms.manipulate_data.ManipulateDataTransform.candidate_untransforms",
    "bofire.data_models.transforms.manipulate_data.ManipulateDataTransform.experiment_transforms",
}

# Classes that do not yet carry a docstring of their own. Only ever remove entries.
UNDOCUMENTED_CLASSES = {
    "bofire.data_models.acquisition_functions.acquisition_function.AcquisitionFunction",
    "bofire.data_models.acquisition_functions.acquisition_function.MultiObjectiveAcquisitionFunction",
    "bofire.data_models.acquisition_functions.acquisition_function.SingleObjectiveAcquisitionFunction",
    "bofire.data_models.acquisition_functions.acquisition_function.qEHVI",
    "bofire.data_models.acquisition_functions.acquisition_function.qEI",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogEHVI",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogEI",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEHVI",
    "bofire.data_models.acquisition_functions.acquisition_function.qLogNEI",
    "bofire.data_models.acquisition_functions.acquisition_function.qMFHVKG",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEHVI",
    "bofire.data_models.acquisition_functions.acquisition_function.qNEI",
    "bofire.data_models.acquisition_functions.acquisition_function.qNegIntPosVar",
    "bofire.data_models.acquisition_functions.acquisition_function.qPI",
    "bofire.data_models.acquisition_functions.acquisition_function.qSR",
    "bofire.data_models.acquisition_functions.acquisition_function.qUCB",
    "bofire.data_models.base.BaseModel",
    "bofire.data_models.dataframes.dataframes.CandidateOutputValue",
    "bofire.data_models.dataframes.dataframes.CandidateRow",
    "bofire.data_models.dataframes.dataframes.Candidates",
    "bofire.data_models.dataframes.dataframes.DataFrame",
    "bofire.data_models.dataframes.dataframes.DataFrame[CandidateRow]",
    "bofire.data_models.dataframes.dataframes.DataFrame[ExperimentRow]",
    "bofire.data_models.dataframes.dataframes.ExperimentOutputValue",
    "bofire.data_models.dataframes.dataframes.ExperimentRow",
    "bofire.data_models.dataframes.dataframes.Experiments",
    "bofire.data_models.dataframes.dataframes.OutputValue",
    "bofire.data_models.dataframes.dataframes.Row",
    "bofire.data_models.dataframes.dataframes.Row[CandidateOutputValue]",
    "bofire.data_models.dataframes.dataframes.Row[ExperimentOutputValue]",
    "bofire.data_models.descriptor_generators.generators.Fingerprints",
    "bofire.data_models.descriptor_generators.generators.Fragments",
    "bofire.data_models.descriptor_generators.generators.MordredDescriptors",
    "bofire.data_models.domain.constraints.Constraints",
    "bofire.data_models.domain.features.Features",
    "bofire.data_models.domain.features._BaseFeatures[Annotated[Union[ContinuousOutput, CategoricalOutput], FieldInfo(annotation=NoneType, required=True, discriminator='type')]]",
    "bofire.data_models.domain.features._BaseFeatures[Annotated[Union[DiscreteInput, CategoricalInput, ContinuousInput, ContinuousOutput, CategoricalOutput, CategoricalTaskInput, ContinuousTaskInput, SumFeature, MeanFeature, WeightedSumFeature, ProductFeature, InterpolateFeature, CloneFeature], FieldInfo(annotation=NoneType, required=True, discriminator='type')]]",
    "bofire.data_models.domain.features._BaseFeatures[Annotated[Union[DiscreteInput, CategoricalInput, ContinuousInput, ContinuousTaskInput, CategoricalTaskInput], FieldInfo(annotation=NoneType, required=True, discriminator='type')]]",
    "bofire.data_models.domain.features._BaseFeatures[Annotated[Union[SumFeature, MeanFeature, WeightedSumFeature, ProductFeature, InterpolateFeature, CloneFeature], FieldInfo(annotation=NoneType, required=True, discriminator='type')]]",
    "bofire.data_models.features.categorical.CategoricalOutput",
    "bofire.data_models.kernels.aggregation.AdditiveKernel",
    "bofire.data_models.kernels.aggregation.MultiplicativeKernel",
    "bofire.data_models.kernels.aggregation.ScaleKernel",
    "bofire.data_models.kernels.categorical.CategoricalKernel",
    "bofire.data_models.kernels.categorical.HammingDistanceKernel",
    "bofire.data_models.kernels.conditional.WedgeKernel",
    "bofire.data_models.kernels.continuous.ContinuousKernel",
    "bofire.data_models.kernels.continuous.InfiniteWidthBNNKernel",
    "bofire.data_models.kernels.continuous.LinearKernel",
    "bofire.data_models.kernels.continuous.MaternKernel",
    "bofire.data_models.kernels.continuous.PolynomialKernel",
    "bofire.data_models.kernels.continuous.RBFKernel",
    "bofire.data_models.kernels.fidelity.DownsamplingKernel",
    "bofire.data_models.kernels.kernel.AggregationKernel",
    "bofire.data_models.kernels.kernel.FeatureSpecificKernel",
    "bofire.data_models.kernels.kernel.Kernel",
    "bofire.data_models.kernels.molecular.MolecularKernel",
    "bofire.data_models.kernels.molecular.TanimotoKernel",
    "bofire.data_models.strategies.doe.AOptimalityCriterion",
    "bofire.data_models.strategies.doe.DOptimalityCriterion",
    "bofire.data_models.strategies.doe.DoEOptimalityCriterion",
    "bofire.data_models.strategies.doe.DoEStrategy",
    "bofire.data_models.strategies.doe.EOptimalityCriterion",
    "bofire.data_models.strategies.doe.GOptimalityCriterion",
    "bofire.data_models.strategies.doe.IOptimalityCriterion",
    "bofire.data_models.strategies.doe.KOptimalityCriterion",
    "bofire.data_models.strategies.doe.OptimalityCriterion",
    "bofire.data_models.strategies.doe.SpaceFillingCriterion",
    "bofire.data_models.strategies.predictives.acqf_optimization.AcquisitionOptimizer",
    "bofire.data_models.strategies.predictives.acqf_optimization.BotorchOptimizer",
    "bofire.data_models.strategies.predictives.botorch.BotorchStrategy",
    "bofire.data_models.strategies.predictives.enting.EntingStrategy",
    "bofire.data_models.strategies.predictives.mobo.MoboStrategy",
    "bofire.data_models.strategies.predictives.mobo.ReferencePoint",
    "bofire.data_models.strategies.predictives.mobo.ReferenceValue",
    "bofire.data_models.strategies.predictives.multi_fidelity.MultiFidelityVarianceBasedStrategy",
    "bofire.data_models.strategies.predictives.multi_fidelity_knowledge_gradient.MultiFidelityHVKGStrategy",
    "bofire.data_models.strategies.predictives.multiobjective.MultiobjectiveStrategy",
    "bofire.data_models.strategies.predictives.predictive.PredictiveStrategy",
    "bofire.data_models.strategies.predictives.qparego.QparegoStrategy",
    "bofire.data_models.strategies.predictives.sobo.AdditiveSoboStrategy",
    "bofire.data_models.strategies.predictives.sobo.CustomSoboStrategy",
    "bofire.data_models.strategies.predictives.sobo.MultiplicativeSoboStrategy",
    "bofire.data_models.strategies.predictives.sobo.SoboBaseStrategy",
    "bofire.data_models.strategies.predictives.sobo.SoboStrategy",
    "bofire.data_models.strategies.stepwise.conditions.AlwaysTrueCondition",
    "bofire.data_models.strategies.stepwise.conditions.CombiCondition",
    "bofire.data_models.strategies.stepwise.conditions.Condition",
    "bofire.data_models.strategies.stepwise.conditions.NumberOfExperimentsCondition",
    "bofire.data_models.strategies.stepwise.conditions.SingleCondition",
    "bofire.data_models.strategies.stepwise.stepwise.Step",
    "bofire.data_models.strategies.stepwise.stepwise.StepwiseStrategy",
    "bofire.data_models.strategies.strategy.Strategy",
    "bofire.data_models.surrogates.bnn.SingleTaskIBNNSurrogate",
    "bofire.data_models.surrogates.deterministic.LinearDeterministicSurrogate",
    "bofire.data_models.surrogates.empirical.EmpiricalSurrogate",
    "bofire.data_models.surrogates.fully_bayesian.FullyBayesianSingleTaskGPSurrogate",
    "bofire.data_models.surrogates.linear.LinearSurrogate",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPHyperconfig",
    "bofire.data_models.surrogates.mixed_single_task_gp.MixedSingleTaskGPSurrogate",
    "bofire.data_models.surrogates.mlp.ClassificationMLPEnsemble",
    "bofire.data_models.surrogates.mlp.MLPEnsemble",
    "bofire.data_models.surrogates.mlp.RegressionMLPEnsemble",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPHyperconfig",
    "bofire.data_models.surrogates.multi_task_gp.MultiTaskGPSurrogate",
    "bofire.data_models.surrogates.polynomial.PolynomialSurrogate",
    "bofire.data_models.surrogates.random_forest.RandomForestSurrogate",
    "bofire.data_models.surrogates.scaler.Normalize",
    "bofire.data_models.surrogates.scaler.Scaler",
    "bofire.data_models.surrogates.scaler.Standardize",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPHyperconfig",
    "bofire.data_models.surrogates.single_task_gp.SingleTaskGPSurrogate",
    "bofire.data_models.surrogates.surrogate.Surrogate",
    "bofire.data_models.surrogates.tanimoto_gp.TanimotoGPSurrogate",
    "bofire.data_models.surrogates.trainable.Hyperconfig",
    "bofire.data_models.surrogates.trainable.TrainableSurrogate",
    "bofire.data_models.surrogates.trainable_botorch.TrainableBotorchSurrogate",
    "bofire.data_models.transforms.drop_data.DropDataTransform",
    "bofire.data_models.transforms.transform.Transform",
}


def _collect_data_model_classes() -> Dict[str, Type[BaseModel]]:
    """Return every pydantic model defined under `bofire.data_models`, keyed by path.

    Import errors are deliberately not caught: a module that cannot be imported would
    otherwise drop out of the parametrization and leave a whole package unenforced.
    """
    classes: Dict[str, Type[BaseModel]] = {}
    for module_info in pkgutil.walk_packages(
        bofire.data_models.__path__,
        bofire.data_models.__name__ + ".",
    ):
        module = importlib.import_module(module_info.name)
        for obj in vars(module).values():
            if (
                isinstance(obj, type)
                and issubclass(obj, BaseModel)
                and obj.__module__.startswith("bofire.data_models")
            ):
                classes[f"{obj.__module__}.{obj.__qualname__}"] = obj
    return classes


DATA_MODEL_CLASSES = _collect_data_model_classes()


def _own_field_names(cls: Type[BaseModel]) -> List[str]:
    """Return the fields declared on `cls` itself, ignoring the `type` discriminator.

    Inherited fields are documented on the class that declares them. Checking them
    again here would report one undocumented base class field once per subclass.
    """
    annotations = getattr(cls, "__annotations__", {})
    return [name for name in cls.model_fields if name in annotations and name != "type"]


def _undocumented_fields() -> set:
    return {
        f"{path}.{name}"
        for path, cls in DATA_MODEL_CLASSES.items()
        for name in _own_field_names(cls)
        if not cls.model_fields[name].description
    }


def _undocumented_classes() -> set:
    return {
        path
        for path, cls in DATA_MODEL_CLASSES.items()
        if not cls.__dict__.get("__doc__")
    }


@pytest.mark.parametrize("path", sorted(DATA_MODEL_CLASSES))
def test_own_fields_have_descriptions(path: str):
    cls = DATA_MODEL_CLASSES[path]
    missing = {
        f"{path}.{name}"
        for name in _own_field_names(cls)
        if not cls.model_fields[name].description
    }
    assert not missing - UNDOCUMENTED_FIELDS, (
        f"{sorted(missing - UNDOCUMENTED_FIELDS)} lack `Field(description=...)`. "
        "Field prose belongs in the field, not in an `Attributes:` docstring block, "
        "because only the former reaches `model_json_schema()`."
    )


@pytest.mark.parametrize("path", sorted(DATA_MODEL_CLASSES))
def test_classes_have_docstrings(path: str):
    cls = DATA_MODEL_CLASSES[path]
    if cls.__dict__.get("__doc__"):
        return
    assert path in UNDOCUMENTED_CLASSES, (
        f"{path} has no docstring of its own. State what it is and when to pick it "
        "over its siblings in the union."
    )


def test_field_allowlist_has_no_stale_entries():
    stale = UNDOCUMENTED_FIELDS - _undocumented_fields()
    assert not stale, (
        f"{sorted(stale)} are documented (or no longer exist) but still listed in "
        "UNDOCUMENTED_FIELDS. Delete them: the allowlist may only shrink."
    )


def test_class_allowlist_has_no_stale_entries():
    stale = UNDOCUMENTED_CLASSES - _undocumented_classes()
    assert not stale, (
        f"{sorted(stale)} are documented (or no longer exist) but still listed in "
        "UNDOCUMENTED_CLASSES. Delete them: the allowlist may only shrink."
    )
