from bofire.plot.cv_folds import plot_cv_folds_plotly
from bofire.plot.duplicates import plot_duplicates_plotly
from bofire.plot.feature_importance import plot_feature_importance_by_feature_plotly
from bofire.plot.gp_slice import plot_gp_slice_plotly
from bofire.plot.objective import plot_objective_plotly
from bofire.plot.prior import plot_prior_pdf_plotly
